### ISSUE TITLE
bug:  angular19 

### ISSUE THREAD

**Issue by UTSOURCE** [rdlabo-team/ionic-angular-collect-icons#4]
### Current Behavior

┌  @rdlabo/ionic-angular-collect-icons
┌  This utility will collect ion-icon from your Ionic Angular project, and generate files to collect and export all icons. 
DirectoryNotFoundError: Directory not found: F:/net/UtApp/.vscode/typings
    at #getDirectoryNotFoundErrorIfNecessary (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:2009:50)  
    at RealFileSystemHost.readDirSync (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:1918:61)
    at TransactionalFileSystem.readDirSync (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:2549:56)    
    at FileUtils.getDescendantDirectories (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:1593:47)     
    at getDescendantDirectories.next (<anonymous>)
    at FileUtils.getDescendantDirectories (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:1597:30)     
    at getDescendantDirectories.next (<anonymous>)
    at FileUtils.getDescendantDirectories (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:1597:30)     
    at getDescendantDirectories.next (<anonymous>)
    at DirectoryCoordinator.addDirectoryAtPathIfExists (F:\net\UtApp\node_modules\ts-morph\dist\ts-morph.js:19088:24) {    
  path: 'F:/net/UtApp/.vscode/typings',
  code: 'ENOENT'
}

### Expected Behavior

It should compile successfully normally

### Steps to Reproduce

npx @rdlabo/ionic-angular-collect-icons --initialize true

### Additional Information

┌  @rdlabo/ionic-angular-collect-icons
┌  This utility will collect ion-icon from your Ionic Angular project, and generate files to collect and export all icons. 
DirectoryNotFoundError: Directory not found: F:/net/UtApp/.vscode/typings
    at #getDirectoryNotFoundErrorIfNecessary (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:2009:50)  
    at RealFileSystemHost.readDirSync (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:1918:61)
    at TransactionalFileSystem.readDirSync (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:2549:56)    
    at FileUtils.getDescendantDirectories (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:1593:47)     
    at getDescendantDirectories.next (<anonymous>)
    at FileUtils.getDescendantDirectories (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:1597:30)     
    at getDescendantDirectories.next (<anonymous>)
    at FileUtils.getDescendantDirectories (F:\net\UtApp\node_modules\@ts-morph\common\dist\ts-morph-common.js:1597:30)     
    at getDescendantDirectories.next (<anonymous>)
    at DirectoryCoordinator.addDirectoryAtPathIfExists (F:\net\UtApp\node_modules\ts-morph\dist\ts-morph.js:19088:24) {    
  path: 'F:/net/UtApp/.vscode/typings',
  code: 'ENOENT'
}

**Comment by UTSOURCE** [comment]
You must add the following two folders to avoid errors

.vscode\typings\cordova-ionic\plugins
.vscode\typings\jquery
